package edu.epam.bookie.model.sport;

public enum Team {
    MANCHESTER_CITY,
    MANCHESTER_UNITED,
    LEICESTER_CITY,
    CHELSEA,
    WEST_HAM_UNITED,
    LIVERPOOL,
    EVERTON,
    ASTON_VILLA,
    TOTTENHAM_HOTSPUR,
    ARSENAL,
    LEEDS_UNITED,
    WOLVERHAMPTON_WANDERERS,
    SOUTHAMPTON,
    CRYSTAL_PALACE,
    BURNLEY,
    BRIGHTON_AND_HOVE_ALBION,
    NEWCASTLE_UNITED,
    FULHAM,
    WEST_BROMWICH_ALBION,
    SHEFFIELD_UNITED
}
